event_system_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  
from django.conf.urls.static import static  
from .views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_page,name='home'),
    path('events/', include('events.urls')),  
    path('auth/', include('user_auth.urls')),  
    path('register/event/',include('registrations.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls import path
from .views import list_events_user,create_event,edit_event,delete_event,details_event,get_profile,list_events

urlpatterns = [
    path("",list_events,name="events"),
    path('myEvents/',list_events_user,name='my_events'),
    path('create/',create_event,name='create_event'),
    path('details/<int:id>/', details_event, name='details_event'),
    path('edit/<int:id>/', edit_event, name='edit_event'),
    path('delete/<int:id>/', delete_event, name='delete_event'),
    path('profile/',get_profile,name='profile'),
    
]

user_auth/urls.py
from django.urls import path,include
from .views import custom_login,register,custom_logout

urlpatterns = [
    path('login/',custom_login,name='login'),
    path('register/',register,name='register'),
    path('logout/',custom_logout,name='logout')
]

user_auth/models.py
from django.db import models

# Create your models here.

user_auth/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome do usuario'}),
        label='Nome do usuario'
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Senha'}),
        label='Senha'
    )


class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=30,
        required=True,
        label="Primeiro Nome",
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'id': 'inputFirstName',
            'placeholder': 'Digite seu primeiro nome',
        })
    )
    last_name = forms.CharField(
        max_length=30,
        required=True,
        label="Sobrenome",
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'id': 'inputLastName',
            'placeholder': 'Digite seu sobrenome',
        })
    )
    email = forms.EmailField(
        required=True,
        label="Endereço de E-mail",
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'id': 'inputEmail',
            'placeholder': 'nome@exemplo.com',
        })
    )
    password1 = forms.CharField(
        label="Senha",
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'id': 'inputPassword',
            'placeholder': 'Crie uma senha',
        })
    )
    password2 = forms.CharField(
        label="Confirme a Senha",
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'id': 'inputPasswordConfirm',
            'placeholder': 'Confirme a senha',
        })
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']

    def clean_first_name(self):
        username = self.cleaned_data.get('first_name')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("Este nome de usuário já está em uso.")
        return username
    
    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Este e-mail já está em uso. Por favor, escolha outro.")
        return email
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = self.cleaned_data['first_name'] 
        if commit:
            user.save()
        return user

user_auth/views.py
from django.shortcuts import render,redirect
from .forms import CustomAuthenticationForm,CustomUserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login,logout

def custom_login(request):
       if request.method == 'GET':
            form = CustomAuthenticationForm()
            return render(request, 'login.html', {'form': form})
    
       form = CustomAuthenticationForm(request, data=request.POST)
       if form.is_valid():
              username = form.cleaned_data.get('username')
              password = form.cleaned_data.get('password')
              user = authenticate(request, username=username, password=password)
              if user is None:
                      return render(request, 'login.html', {'form': form})
              login(request, user)
              return redirect('events')  
       return render(request, 'login.html', {'form': form})

def register(request):
    if request.method == 'GET':
        form = CustomUserCreationForm()
        return render(request, 'register.html',{'form':form})

    form = CustomUserCreationForm(request.POST)
    if form.is_valid():
       form.save()
       return redirect('login')
    return render(request, 'register.html', {'form': form})

@login_required
def custom_logout(request):
     logout(request)
     return redirect('login')

user_auth/templates/base-auth.html
{% load static%}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="{%block 'description' %} {% endblock %}" />
        <meta name="author" content="vzincoder" />
        <title>{% block 'title' %} {%endblock%}</title>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="bg-dark">
        <div id="layoutAuthentication">
            {% include "header-apresentation.html" %} 
            <div id="layoutAuthentication_content">
                <main>
                    {% block 'content' %}

                    {% endblock %} 
                </main>
            </div>
            <div id="layoutAuthentication_footer">
                <footer class="bg-primary text-center py-3 mt-auto text-white">
                    <p class="mb-0">&copy; 2025 vzincoder - Todos os direitos reservados.</p>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

user_auth/templates/login.html
{% extends "base-auth.html" %}
{% block 'description' %}Página de login{%endblock%}
{% block 'title' %}Login{%endblock%}
{% block 'content' %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-5">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header"><h3 class="text-center font-weight-light my-4">Login</h3></div>
                {% if form.non_field_errors %}
                    <div class="alert alert-danger m-4">
                        {% for error in form.non_field_errors %}
                            <p>{{ error }}</p>
                         {% endfor %}
                    </div>
                {% endif %}
                <div class="card-body">
                    <form method="post" action="{% url 'login' %}">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            {{ form.username }}
                            <label for="id_username">Nome do usuario</label>
                            {% if form.username.errors %}
                                <div class="text-danger small">
                                        {{ form.username.errors.0 }}
                                </div>
                            {% endif %}
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.password }}
                            <label for="id_password">Senha</label>
                            {% if form.password.errors %}
                                <div class="text-danger small">
                                        {{ form.password.errors.0 }}
                                </div>
                            {% endif %}
                        </div>
                        <div class=" d-flex align-items-center justify-content-between mt-4 mb-0 form-check mb-3">
                            <div>
                                <input class="form-check-input" id="inputRememberPassword" type="checkbox" value="" />
                                <label class="form-check-label" for="inputRememberPassword">Lembrar Senha</label>
                            </div>
                            <button type="submit" class="btn btn-primary">Login</button>
                        </div>
                    </form>
                </div>
                <div class="card-footer text-center py-3">
                    <div class="small"><a href="{% url 'register' %}">Precisa de uma conta? Inscrever-se!</a></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

user_auth/templates/register.html
{% extends "base-auth.html" %}
{% block 'description' %}Página de Cadastro{% endblock %}
{% block 'title' %}Criar conta{% endblock %}
{% block 'content' %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-7">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header">
                    <h3 class="text-center font-weight-light my-4">Criar Conta</h3>
                </div>
                <div class="card-body">
                    {% if form.non_field_errors %}
                        <div class="alert alert-danger">
                            {% for error in form.non_field_errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}

                    <form method="post" action="{% url 'register' %}">
                        {% csrf_token %}

                        <div class="row mb-3">
                            <div class="col-md-6">
                                <div class="form-floating mb-3 mb-md-0">
                                    {{ form.first_name }}
                                    <label for="id_first_name">Primeiro Nome</label>
                                    {% if form.first_name.errors %}
                                        <div class="text-danger small">
                                            {{ form.first_name.errors.0 }}
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-floating">
                                    {{ form.last_name }}
                                    <label for="id_last_name">Sobrenome</label>
                                    {% if form.last_name.errors %}
                                        <div class="text-danger small">
                                            {{ form.last_name.errors.0 }}
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>

                        <div class="form-floating mb-3">
                            {{ form.email }}
                            <label for="id_email">Endereço de E-mail</label>
                            {% if form.email.errors %}
                                <div class="text-danger small">
                                    {{ form.email.errors.0 }}
                                </div>
                            {% endif %}
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-6">
                                <div class="form-floating mb-3 mb-md-0">
                                    {{ form.password1 }}
                                    <label for="id_password1">Senha</label>
                                    {% if form.password1.errors %}
                                        <div class="text-danger small">
                                            {{ form.password1.errors.0 }}
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-floating mb-3 mb-md-0">
                                    {{ form.password2 }}
                                    <label for="id_password2">Confirme a Senha</label>
                                    {% if form.password2.errors %}
                                        <div class="text-danger small">
                                            {{ form.password2.errors.0 }}
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>

                        <div class="mt-4 mb-0">
                            <div class="d-grid">
                                <button class="btn btn-primary btn-block" type="submit">Criar Conta</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="card-footer text-center py-3">
                    <div class="small"><a href="{% url 'login' %}">Já possui uma conta? Faça login</a></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}